AllCops:
  TargetRubyVersion: 2.0

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/IndentHash:
  Enabled: false
