sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.1.5
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
  - 2.3.1
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rubocop
  - bundle exec rspec
