sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.0
  - 2.3.1
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rubocop
  - bundle exec rspec
